@startuml PlateformeDeTrading


    class Utilisateur {
      + nom : String
      - email : String
      - motDePasse : String
      - inscrire()
      - seConnecter()
      - seDéconnecter()
    }

    class TicketDeSupport {
      + sujet : String
      + description : String
      + statut : boolean
      + dateCreation : Date
      + résoluLe : Date
    }

    class Trader {
    + estVérifié : Boolean
    -  mettreAJourProfil()
    -  créerOrdre()
    -  modifierOrdre()
    -  annulerOrdre() 
    -  créerAlerte()
    -  modifierAlerte() 
    -  annulerAlerte() 
    -  creeTicket()
    -  déposer()
    -  retirer()

    }

    class Agent {
      
    -  gérerTicketsSupport()
    -  vérifierIdentitéUtilisateur()

    }



class Ordre {

 + paireMarché : String
 + type : String
 + statut : String
 + montant : double
 + prixEntree : double
 + prixCible : double
 + dateCreation : Date
 + exécutéLe : Date

}



class Marché {
   + paire : String
   + prixActuel : doube
   + volume24h : double
   + carnetOrdres : Ordre [ ]
  - mettreAJourDonnés()
  - apprierOrdres()
  + afficherGraphique()
}


class Alerte {
  + prixCible : double
  + status : boolean
  + dateCreation : Date
  + dateExecution : Date
  - vérifierCondition()
  - notifier()
}

    
    class Portefeuille {
      + adresse
      - Map<String, Double> devises  
      + obtenirSolde()
      - mettreAJourSolde()
    }

    class Transaction {
       + type : String
       + montant : double
       + devise : String
       + statut : StatutTransaction
       + dateCreation : Date
    }

Utilisateur <|-- Agent 
Utilisateur <.. Agent 
Utilisateur <|-- Trader 
Trader"0..*" --> "1"TicketDeSupport : creer 
Agent"0..*" --> "1"TicketDeSupport : traiter 
Trader"0..*" o-- "1"Transaction : associer
Trader"0..*" --> "1"Ordre : creer
Trader"1..*" *-- "1"Portefeuille 
Ordre"1" --* "0..*"Marché
Trader"0..*" -- "1"Alerte : creer
Trader"0..*" -- "1"Alerte : recevoir 
Marché <.. Alerte 
@enduml