@startuml StateDiagramOrdre

title Diagramme d'États pour la Classe Ordre

state Ouvert
state Verification
state PartiellementExécuté as "Partiellement Exécuté"
state Exécuté
state Annulé
state rejetee 

[*] --> Verification 
Verification --> Ouvert :  [Valide]
Verification --> rejetee :  [non valide]

Ouvert --> PartiellementExécuté :   [Match Partiel]
Ouvert --> Exécuté :   [Match Complet]
Ouvert --> Annulé : annulation

PartiellementExécuté --> Exécuté : [Match du Reste]

rejetee --> [*]
Annulé --> [*]
Exécuté --> [*]

@enduml