@startuml tradingPlatform
left to right direction
skinparam actorStyle awesome

actor "utilisateur" as user
actor "Trader" as t
actor "Agent" as a
actor "Réseau Blockchain" as blockchainNetwork
actor "Passerelle de Paiement" as PaymentGateway
actor "trading view api" as trading_api

a <|-- user
t <|-- user

rectangle "Plateforme de Trading" {

        usecase "Traiter Transaction Crypto" as miningTransaction
        usecase "Traiter Transaction Fiat" as fiatAuthConf
        usecase "Traiter Ordre" as processOrder


        usecase "Annuler Ordre" as CancelOrder
        usecase "Visualisation Graphique" as chart_visual
        usecase "traiter visualistaion graphique" as traitgraph
        chart_visual ..> traitgraph : <<include>> 
         traitgraph <-- trading_api 
        t --> chart_visual
                 

        usecase "Choisir Time Frame" as time_frame

        usecase "Voir Historique des Trades" as hist_trade

        usecase "Exporter Historique des Trades" as export

        usecase "Demander Support Client" as clientSupport
        usecase "passer ordre" as passorder
        usecase "Acheter Cryptomonnaie" as buy
        usecase "Vendre Cryptomonnaie" as sell
        passorder <|-- buy
        passorder <|-- sell 

        chart_visual <.. time_frame : <<extend>>
        hist_trade <.. export : <<extend>>



buy ..> processOrder : <<include>>
sell ..> processOrder : <<include>>

        usecase "gestion portfeuille" as gererPortfeuille
        usecase "Déposer" as deposit
        usecase "Dépôt Crypto" as depositCrypto
        usecase "Dépôt Fiat" as depositFiat
        usecase "Retirer" as withdraw
        usecase "Retrait Crypto" as withdrawCrypto
        usecase "Retrait Fiat" as withdrawFiat
        gererPortfeuille <|-- deposit
        gererPortfeuille <|-- withdraw 
        gererPortfeuille <|-- hist_trade 

        usecase "Vérifier Historique Transactions" as transactionHistory
        usecase "Vérifier Solde Portefeuille" as balanceHistory
        usecase "Exporter Historique Transactions" as transactionHistory_export

        withdraw <|-- withdrawFiat
        withdraw <|-- withdrawCrypto
        deposit <|-- depositCrypto
        deposit <|-- depositFiat
        transactionHistory <.. transactionHistory_export : <<extend>>



withdrawCrypto ..> miningTransaction  : <<include>>
depositCrypto ..> miningTransaction : <<include>>
withdrawFiat ..> fiatAuthConf  : <<include>>
depositFiat ..> fiatAuthConf  : <<include>>


        usecase "Vérifier Historique Alertes" as notif_history
        usecase "Créer Alerte de Prix" as createAlert
        usecase "gestion alertes" as gererAlerets
        usecase "Modifier Alerte" as modifyAlert
        usecase "Supprimer Alerte" as deleteAlert
        gererAlerets <|-- modifyAlert
        gererAlerets <|-- deleteAlert 




        usecase "Connexion" as login
        usecase "Vérifier Détails Connexion" as verifyLogin
        usecase "Vérifier Identité Utilisateur" as verify_identity

        login ..> verifyLogin : <<include>>
        usecase "s'incrire" as register
        register ..> verify_identity : <<include>>


        usecase "Gérer Utilisateurs" as manage_users
        usecase "Traiter Problèmes Support" as handleSupport

        usecase "gestion ordres" as gestionOrdre
        usecase "modifer ordres" as modifOrder
        gestionOrdre <|-- passorder
        gestionOrdre <|-- CancelOrder 
        gestionOrdre <|-- modifOrder 
        gererPortfeuille <|-- balanceHistory 

}



t --> gestionOrdre 
t --> clientSupport

t --> gererPortfeuille 
t --> transactionHistory

user --> register
user --> login

gererAlerets <|-- createAlert
gererAlerets  <|-- notif_history
t --> gererAlerets 

a --> manage_users
manage_users <|-- handleSupport
manage_users <|-- verify_identity 


fiatAuthConf <-- PaymentGateway
miningTransaction <-- blockchainNetwork

@enduml